### ISSUE TITLE
default user password for the console?

### ISSUE THREAD

**Issue by pletisan** [npwalker/pe-razor-vagrant-stack#8]
Hi, 

first thanks for this setup! I'm considering using Razor for bare-metal provisioning and having vagrant conf to try it out is very helpful.

Could you provide more details on default credentials for the boxes and PE console?

Thanks,
Igor

**Comment by npwalker** [comment]
Hi @pletisan, 

I updated the README with these notes.  The default credentials for the console are admin with password puppetlabs.  

If you'd like to login to any of the boxes you can do so with `vagrant ssh <box_name>` if you want more details on how vagrant works then you can check out their website.  

http://docs.vagrantup.com/v2/getting-started/index.html

I'm going to close this out but let me know if you run into any more issues.
